const language = {
  es: {
    menu: "Menú",
    about_us: "Sobre Nosotros",
    language_label: "Idioma:",
    welcome_text: "Bienvenid@ a Honey Food, donde celebramos la auténtica comida callejera colombiana con cada bocado. Desde nuestras arepas hechas a mano hasta los chorizos llenos de sabor, traemos un pedacito de Colombia a las calles de Toronto. Ven y disfruta de una experiencia culinaria llena de tradición, sazón y cariño. ¡Estás en casa!",
    featured_dishes: "Platillos Destacados",
    dish1_title: "Chicharron",
    dish1_desc: "Clásico chicharrón crujiente Colombiano.",
    dish2_title: "Arepa de Choclo",
    dish2_desc: "Hecha a mano, con maíz dulce y queso.",
    dish3_title: "Papas Chorreadas",
    dish3_desc: "Irresistible combinacion de hogao con papita cocida.",
    dish4_title: "Perro Caliente",
    dish4_desc: "Salchicha llena de sabor combinada con el mejor pan de perro.",
    testimonials_title: "Lo que dicen nuestros clientes",
    test1: "¡Increíble sabor! Me recordó a casa. Volveré sin duda.",
    test2: "El mejor lugar para probar comida colombiana auténtica.",
    test3: "Excelente atención y la comida estaba deliciosa. Me encantaron las arepas.",
    test4: "Un pedacito de Colombia en Toronto. ¡Los chorizos son espectaculares!",
    test5: "Todo muy fresco y lleno de sabor. ¡100% recomendado!",
    footer: "Comida callejera colombiana en Toronto | Hecho con ❤️ por emprendedores"
  },
  en: {
    menu: "Menu",
    about_us: "About Us",
    language_label: "Language:",
    welcome_text: "Welcome to Honey Food, where we celebrate authentic Colombian street food with every bite. From our handmade arepas to the flavorful sausages, we bring a piece of Colombia to the streets of Toronto. Come and enjoy a culinary experience full of tradition, flavor, and love. You're at home!",
    featured_dishes: "Featured Dishes",
    dish1_title: "Chicharron",
    dish1_desc: "Classic crispy Colombian pork rind.",
    dish2_title: "Arepa de Choclo",
    dish2_desc: "Handmade with sweet corn and cheese.",
    dish3_title: "Papas Chorreadas",
    dish3_desc: "Irresistible combination of hogao sauce with boiled potatoes.",
    dish4_title: "Hot Dog",
    dish4_desc: "Flavorful sausage combined with the best hot dog bun.",
    testimonials_title: "What our customers say",
    test1: "Amazing flavor! Reminded me of home. I'll definitely come back.",
    test2: "The best place to try authentic Colombian food.",
    test3: "Excellent service and the food was delicious. Loved the arepas.",
    test4: "A little piece of Colombia in Toronto. The sausages are spectacular!",
    test5: "Everything very fresh and full of flavor. 100% recommended!",
    footer: "Colombian Street Food in Toronto | Made with ❤️ by entrepreneurs"
  }
};

const translations = {
  es: {
    title: "HONEY FOOD",
    home: "Inicio",
    about_us: "Sobre Nosotros",
    search_placeholder: "Buscar en el menú...",
    product_arepa_choclo: "Arepa de Choclo",
    desc_arepa_choclo: "Deliciosa arepa de maíz dulce, ideal para acompañar tu comida.",
    product_papas_chorreadas: "Papas Chorreadas",
    desc_papas_chorreadas: "Papas con salsa de queso y bacon, un plato lleno de sabor.",
    product_hogao: "Hogao",
    desc_hogao: "Salsa tradicional colombiana, ideal para acompañar tus platos favoritos.",
    product_chicharron_arepa: "Chicharron con Arepa",
    desc_chicharron_arepa: "Exquisitos chicharrones colombianos, preparados al mejor estilo.",
    product_rellenas: "Rellenas",
    desc_rellenas: "Empanadas rellenas de carne, pollo o queso, perfectas para cualquier momento.",
    product_hamburguesas: "Hamburguesas",
    desc_hamburguesas: "Hamburguesas jugosas con carne 100% fresca, acompañadas de lo mejor.",
    product_papas_locas: "Papas Locas",
    desc_papas_locas: "Papas fritas con salsas y toppings irresistibles.",
    product_morrongos: "Morrongos",
    desc_morrongos: "Un plato típico que no te puedes perder, preparado con todo el sabor colombiano.",
    product_salchipapas: "Salchipapas",
    desc_salchipapas: "Salchichas acompañadas de papas fritas, un clásico que todos disfrutan.",
    product_desgranados: "Desgranados",
    desc_desgranados: "Deliciosa mezcla de arroz, frijoles y carne, perfecta para cualquier ocasión.",
    product_salsa_tartara: "Salsa Tártara",
    desc_salsa_tartara: "Salsa cremosa perfecta para acompañar carnes y pescados.",
    product_salsa_pina: "Salsa de Piña",
    desc_salsa_pina: "Salsa de piña fresca, el toque dulce perfecto para tus platos.",
    product_empanadas: "Empanadas",
    desc_empanadas: "Empanadas rellenas con carne o pollo, un bocado delicioso.",
    product_perros_calientes: "Perros Calientes",
    desc_perros_calientes: "Sabrosos perritos calientes, una opción rápida y deliciosa.",
    add_to_cart: "Agregar al carrito",
    your_order: "Tu pedido",
    send_order: "Enviar pedido por WhatsApp",
    empty_cart: "🗑️ Vaciar carrito",
    scroll_top: "Volver arriba",
    footer_text: "Colombian Street Food in Toronto | Made with ❤️ by entrepreneurs"
  },
  en: {
    title: "HONEY FOOD",
    home: "Home",
    about_us: "About Us",
    search_placeholder: "Search in the menu...",
    product_arepa_choclo: "Corn Arepa",
    desc_arepa_choclo: "Delicious sweet corn arepa, perfect to accompany your meal.",
    product_papas_chorreadas: "Chorreadas Potatoes",
    desc_papas_chorreadas: "Potatoes with cheese sauce and bacon, a flavorful dish.",
    product_hogao: "Hogao",
    desc_hogao: "Traditional Colombian sauce, ideal to accompany your favorite dishes.",
    product_chicharron_arepa: "Pork Crackling with Arepa",
    desc_chicharron_arepa: "Exquisite Colombian pork cracklings, prepared in the best style.",
    product_rellenas: "Rellenas",
    desc_rellenas: "Empanadas filled with meat, chicken or cheese, perfect anytime.",
    product_hamburguesas: "Burgers",
    desc_hamburguesas: "Juicy burgers with 100% fresh meat, accompanied by the best.",
    product_papas_locas: "Crazy Potatoes",
    desc_papas_locas: "French fries with irresistible sauces and toppings.",
    product_morrongos: "Morrongos",
    desc_morrongos: "A typical dish you can't miss, prepared with all Colombian flavor.",
    product_salchipapas: "Salchipapas",
    desc_salchipapas: "Sausages served with french fries, a classic everyone enjoys.",
    product_desgranados: "Desgranados",
    desc_desgranados: "Delicious mix of rice, beans and meat, perfect for any occasion.",
    product_salsa_tartara: "Tartar Sauce",
    desc_salsa_tartara: "Creamy sauce perfect to accompany meats and fish.",
    product_salsa_pina: "Pineapple Sauce",
    desc_salsa_pina: "Fresh pineapple sauce, the perfect sweet touch for your dishes.",
    product_empanadas: "Empanadas",
    desc_empanadas: "Empanadas filled with meat or chicken, a delicious bite.",
    product_perros_calientes: "Hot Dogs",
    desc_perros_calientes: "Tasty hot dogs, a quick and delicious option.",
    add_to_cart: "Add to cart",
    your_order: "Your order",
    send_order: "Send order via WhatsApp",
    empty_cart: "🗑️ Empty cart",
    scroll_top: "Scroll to top",
    footer_text: "Colombian Street Food in Toronto | Made with ❤️ by entrepreneurs"
  }
};

const translations1 = {
      es: {
        title: "HONEY FOOD",
        home: "Inicio",
        menu: "Menú",
        social_media: "REDES SOCIALES",
        opening_hours: "Horarios de Apertura",
        day: "Día",
        open_time: "Hora de Apertura",
        close_time: "Hora de Cierre",
        friday: "Viernes",
        saturday: "Sábado",
        sunday: "Domingo",
        location: "📍 Nuestra Ubicación",
        location_text: "Encuéntranos en el corazón de Toronto. ¡Ven a visitarnos!",
        footer_text: "&copy; 2025 HONEY FOOD | Comida callejera colombiana en Toronto | Hecho con ❤️ por emprendedores"
      },
      en: {
        title: "HONEY FOOD",
        home: "Home",
        menu: "Menu",
        social_media: "SOCIAL MEDIA",
        opening_hours: "Opening Hours",
        day: "Day",
        open_time: "Opening Time",
        close_time: "Closing Time",
        friday: "Friday",
        saturday: "Saturday",
        sunday: "Sunday",
        location: "📍 Our Location",
        location_text: "Find us in the heart of Toronto. Come visit us!",
        footer_text: "&copy; 2025 HONEY FOOD | Colombian Street Food in Toronto | Made with ❤️ by entrepreneurs"
      }
    };


